### ISSUE TITLE
Where is get_weight_initializer() defined?

### ISSUE THREAD

**Issue by KevinLucidyne** [mathildor/TF-SegNet#4]
I see get_weight_initializer() called in AirNet/inference.py but a search doesn't show it in your code or in TensorFlow.

Where is get_weight_initializer() defined?

Thanks!

**Comment by mathildor** [comment]
There is a get_weight_initializer() method defined in AirNet/inference.py at line 219 ?

```
def get_weight_initializer():
    if(FLAGS.conv_init == "var_scale"):
        initializer = tf.contrib.layers.variance_scaling_initializer()
    elif(FLAGS.conv_init == "xavier"):
        initializer=tf.contrib.layers.xavier_initializer()
    else:
        raise ValueError("Chosen weight initializer does not exist")
    return initializer
```

**Comment by KevinLucidyne** [comment]
Thank you.  I have no idea why my search missed that.

**Comment by KevinLucidyne** [comment]
BTW I really like the rewrite of the TensorFlow-SegNet code you've done. Thank you!

**Comment by mathildor** [comment]
No worries, glad I could help :) 
Thank you!
